---

plugin: amazon.aws.aws_ec2

regions:

  - ap-south-1

filters:

  tag:Project:

    - employee-management-system

hostnames:

  - private-ip-address

keyed_groups:

  - prefix: tag

    key: tags.Role

compose:

  ansible_host: private_ip_address
