[devops]

devops ansible_host=DEVOPS_PUBLIC_IP

[frontend]

frontend-1 ansible_host=FRONTEND_PRIVATE_IP

[backend]

backend-1 ansible_host=BACKEND_PRIVATE_IP

[frontend:vars]

ansible_user=ec2-user

[backend:vars]

ansible_user=ec2-user

[devops:vars]

ansible_user=ec2-user

[all:vars]

ansible_python_interpreter=/usr/bin/python3
